CREATE TABLE `user` (
    `id` BIGINT NOT NULL COMMENT '主键ID',
    `name` VARCHAR ( 30 ) DEFAULT NULL COMMENT '姓名',
    `age` INT DEFAULT NULL COMMENT '年龄',
    `email` VARCHAR ( 50 ) DEFAULT NULL COMMENT '邮箱',
    PRIMARY KEY ( `id` )
) ENGINE = INNODB DEFAULT CHARSET = utf8;

CREATE TABLE `role` (
    `id` BIGINT NOT NULL COMMENT '主键ID',
    `name` VARCHAR ( 30 ) DEFAULT NULL COMMENT '名称',
    PRIMARY KEY ( `id` )
) ENGINE = INNODB DEFAULT CHARSET = utf8;